### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by daiscog** [DukeNgn/Dog-facts-API#1]
Chrome blocks cross-origin requests without CORS headers, so requests to this API fail with the error:

> Access to XMLHttpRequest at 'https://dog-facts-api.herokuapp.com/api/v1/resources/dogs' from origin '...' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by cv-net** [comment]
I'm getting this same error, and this didn't help: 
`   const instance = axios.create({
    baseURL: 'https://dog-facts-api.herokuapp.com/api/v1/resources/dogs',
    timeout: 1000,
    headers: { 
        'Access-Control-Allow-Origin': 'https://dog-facts-api.herokuapp.com'
    }
  });`
