### ISSUE TITLE
Attempt to decode JSON with unexpected mimetype: when using Aiohttp

### ISSUE THREAD

**Issue by luciferchase** [DukeNgn/Dog-facts-API#2]
Is there any header or anything to request JSON format explicitly? Because when using aiohttp to get a fact, it results in this error.

**Comment by DukeNgn** [comment]
Hi, thanks for using Dog facts. Unfortunately, the API service is down temporarily and I'm expecting it to get back online tomorrow. I bet that's the reason for your error.

**Comment by luciferchase** [comment]
Okay, I will try again tomorrow. If the problem persists, I will let you know.

**Comment by luciferchase** [comment]
Yes, it works now. Thank you for the great work!!
